# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
